/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package example.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import example.client.model.User

class UserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of User
        //val modelInstance = User()

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `namePretty`
        should("test namePretty") {
            // uncomment below to test the property
            //modelInstance.namePretty shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `familyName`
        should("test familyName") {
            // uncomment below to test the property
            //modelInstance.familyName shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

    }
}
