/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package example.client.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import example.client.api.MyServerApi
import example.client.model.Family

class MyServerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MyServerApi
        //val apiInstance = MyServerApi()

        // to test familyChange
        should("test familyChange") {
            // uncomment below to test familyChange
            //val familyId : kotlin.Int = 56 // kotlin.Int | 
            //val familyPassword : kotlin.String = familyPassword_example // kotlin.String | 
            //val newFamilyPassword : kotlin.String = newFamilyPassword_example // kotlin.String | 
            //val newFamilyName : kotlin.String = newFamilyName_example // kotlin.String | 
            //val result : Family = apiInstance.familyChange(familyId, familyPassword, newFamilyPassword, newFamilyName)
            //result shouldBe ("TODO")
        }

        // to test familyGet
        should("test familyGet") {
            // uncomment below to test familyGet
            //val familyId : kotlin.Int = 56 // kotlin.Int | 
            //val familyPassword : kotlin.String = familyPassword_example // kotlin.String | 
            //val result : Family = apiInstance.familyGet(familyId, familyPassword)
            //result shouldBe ("TODO")
        }

        // to test familyNew
        should("test familyNew") {
            // uncomment below to test familyNew
            //val familyId : kotlin.Int = 56 // kotlin.Int | 
            //val familyPassword : kotlin.String = familyPassword_example // kotlin.String | 
            //val familyName : kotlin.String = familyName_example // kotlin.String | 
            //val result : Family = apiInstance.familyNew(familyId, familyPassword, familyName)
            //result shouldBe ("TODO")
        }

        // to test userChange
        should("test userChange") {
            // uncomment below to test userChange
            //val familyId : kotlin.Int = 56 // kotlin.Int | 
            //val familyPassword : kotlin.String = familyPassword_example // kotlin.String | 
            //val newFamilyPassword : kotlin.String = newFamilyPassword_example // kotlin.String | 
            //val newFamilyName : kotlin.String = newFamilyName_example // kotlin.String | 
            //val result : Family = apiInstance.userChange(familyId, familyPassword, newFamilyPassword, newFamilyName)
            //result shouldBe ("TODO")
        }

        // to test userGet
        should("test userGet") {
            // uncomment below to test userGet
            //val familyId : kotlin.Int = 56 // kotlin.Int | 
            //val familyPassword : kotlin.String = familyPassword_example // kotlin.String | 
            //val result : Family = apiInstance.userGet(familyId, familyPassword)
            //result shouldBe ("TODO")
        }

        // to test userNew
        should("test userNew") {
            // uncomment below to test userNew
            //val familyId : kotlin.Int = 56 // kotlin.Int | 
            //val familyPassword : kotlin.String = familyPassword_example // kotlin.String | 
            //val familyName : kotlin.String = familyName_example // kotlin.String | 
            //val result : Family = apiInstance.userNew(familyId, familyPassword, familyName)
            //result shouldBe ("TODO")
        }

    }
}
