/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package example.client.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name 
 * @param password 
 * @param namePretty 
 * @param users 
 */


data class Family (

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("password")
    val password: kotlin.String? = null,

    @field:JsonProperty("namePretty")
    val namePretty: kotlin.String? = null,

    @field:JsonProperty("users")
    val users: kotlin.collections.List<kotlin.String>? = null

)

