/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package example.client.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param uuid 
 * @param password 
 * @param namePretty 
 * @param type 
 * @param familyName 
 * @param email 
 */


data class User (

    @field:JsonProperty("uuid")
    val uuid: kotlin.String? = null,

    @field:JsonProperty("password")
    val password: kotlin.String? = null,

    @field:JsonProperty("namePretty")
    val namePretty: kotlin.String? = null,

    @field:JsonProperty("type")
    val type: kotlin.Int? = null,

    @field:JsonProperty("familyName")
    val familyName: kotlin.String? = null,

    @field:JsonProperty("email")
    val email: kotlin.String? = null

)

